/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.dasa.wsecosistemasclient;

/**
 *
 * @author Marcos Naves
 */
public class SqlStatic {

    public static String TRIAGEM  = " select req.req_st_codigo,"
            + " der.exa_st_codigo,"
            + " req.req_st_codigoalt,"
            + " udp.udp_st_codigo,"
            + " edp.edp_st_codigo,"
            + " req.uni_st_codigo,"
            + " der.der_in_flag"
            + " from lab_requisicao        req,"
            + " lab_detalherequisicao der,"
            + " lab_unidadedepara     udp,"
            + " lab_examedepara       edp,"
            + " lab_sistema           sis"
            + " where req.req_st_codigo = der.req_st_codigo"
            + " and udp.sis_st_codigo = sis.sis_st_codigo"
            + " and udp.uni_st_codigo = der.uni_st_codigo"
            + " and edp.sis_st_codigo = sis.sis_st_codigo"
            + " and edp.exa_st_codigo = der.exa_st_codigo"
            + " and edp.seq_st_codigo = der.seq_st_codigo"
            + " and udp.uni_st_codigo = sis.uni_st_codigo"
            + " and der.sis_st_codigo is not null"
            + " and der.uni_st_codigo = :uniStCodigo"
            + " and req.req_dt_cadastro >= trunc(sysdate) - 5"
            + " and der.leg_st_codigo in ('003','004')"
            + " and (der_ch_statusintegracao is null or der_ch_statusintegracao = 0)"
            + " order by 1";

    public static String CANCELAMENTO  = " select req.req_st_codigo,"
            + " der.exa_st_codigo,"
            + " req.req_st_codigoalt,"
            + " udp.udp_st_codigo,"
            + " edp.edp_st_codigo,"
            + " req.uni_st_codigo,"
            + " der.der_in_flag"
            + " from lab_requisicao        req,"
            + " lab_detalherequisicao der,"
            + " lab_unidadedepara     udp,"
            + " lab_examedepara       edp,"
            + " lab_sistema           sis"
            + " where req.req_st_codigo = der.req_st_codigo"
            + " and udp.sis_st_codigo = sis.sis_st_codigo"
            + " and udp.uni_st_codigo = der.uni_st_codigo"
            + " and edp.sis_st_codigo = sis.sis_st_codigo"
            + " and edp.exa_st_codigo = der.exa_st_codigo"
            + " and edp.seq_st_codigo = der.seq_st_codigo"
            + " and udp.uni_st_codigo = sis.uni_st_codigo"
            + " and der.sis_st_codigo is not null"
            + " and der.uni_st_codigo = :uniStCodigo"
            + " and req.req_dt_cadastro >= trunc(sysdate) - 5"
            + " and der.leg_st_codigo = '013'"
            + " and (der_ch_statusintegracao is null or der_ch_statusintegracao = 0 or der_ch_statusintegracao = 1)"
            + " order by 1";

    public static String NOVACOLETA  = " select req.req_st_codigo,"
            + " der.exa_st_codigo,"
            + " req.req_st_codigoalt,"
            + " udp.udp_st_codigo,"
            + " edp.edp_st_codigo,"
            + " req.uni_st_codigo,"
            + " der.der_in_flag"
            + " from lab_requisicao        req,"
            + " lab_detalherequisicao der,"
            + " lab_unidadedepara     udp,"
            + " lab_examedepara       edp,"
            + " lab_sistema           sis"
            + " where req.req_st_codigo = der.req_st_codigo"
            + " and udp.sis_st_codigo = sis.sis_st_codigo"
            + " and udp.uni_st_codigo = der.uni_st_codigo"
            + " and edp.sis_st_codigo = sis.sis_st_codigo"
            + " and edp.exa_st_codigo = der.exa_st_codigo"
            + " and edp.seq_st_codigo = der.seq_st_codigo"
            + " and udp.uni_st_codigo = sis.uni_st_codigo"
            + " and der.sis_st_codigo is not null"
            + " and der.uni_st_codigo = :uniStCodigo"
            + " and req.req_dt_cadastro >= trunc(sysdate) - 5"
            + " and der.leg_st_codigo = '020'"
            + " and (der_ch_statusintegracao is null or der_ch_statusintegracao = 0 or der_ch_statusintegracao = 1)"
            + " order by 1";

    public static String RESULTADO  = " select req.req_st_codigo,"
            + " der.exa_st_codigo,"
            + " req.req_st_codigoalt,"
            + " udp.udp_st_codigo,"
            + " edp.edp_st_codigo,"
            + " req.uni_st_codigo,"
            + " der.der_in_flag,"
            + " from lab_requisicao        req,"
            + " lab_detalherequisicao der,"
            + " lab_unidadedepara     udp,"
            + " lab_examedepara       edp,"
            + " lab_sistema           sis"
            + " where req.req_st_codigo = der.req_st_codigo"
            + " and udp.sis_st_codigo = sis.sis_st_codigo"
            + " and udp.uni_st_codigo = der.uni_st_codigo"
            + " and edp.sis_st_codigo = sis.sis_st_codigo"
            + " and edp.exa_st_codigo = der.exa_st_codigo"
            + " and edp.seq_st_codigo = der.seq_st_codigo"
            + " and udp.uni_st_codigo = sis.uni_st_codigo"
            + " and der.sis_st_codigo is not null"
            + " and der.uni_st_codigo = :uniStCodigo"
            + " and req.req_dt_cadastro >= trunc(sysdate) - 5"
            + " and der.leg_st_codigo = '020'"
            + " and (der_ch_statusintegracao is null or der_ch_statusintegracao = 0 or der_ch_statusintegracao = 1 or der_ch_statusintegracao = 2)"
            + " order by 1";
}
